spring:
  application:
    name: 'config-server'
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: ${CONFIG_SERVER_URI:http://localhost:8888}
          username: ${CONFIG_SERVER_USERNAME}
          password: ${CONFIG_SERVER_PASSWORD}
server:
  port: ${PORT:8888}