spring:
  application:
    name: auth-service-api
  data:
    mongodb:
      uri: 'mongodb+srv://help-desk-user:help-desk-user@clusterhelpdesk.nvn4kcx.mongodb.net/helpdeskdb?retryWrites=true&w=majority&appName=ClusterHelpDesk'
jwt.secret: '5KkeABQ3CZ3rGJxR7Wf1BgOHwUY3GOqEH+sJpQ52p8XYD18Nl2VLWvsbRsb79Qv0e0627r3DfP1rSvBa5TvJB0yiQ61RLaoSioXr/sLjuO8='
jwt.expiration: 120000
jwt.expiration-sec.refresh-token: 3600